### ISSUE TITLE
Almost all meshes are missing a skeleton

### ISSUE THREAD

**Issue by Wvave** [Kindrad/Kenshi_IO_Continued#1]
As far as I remember in the all version each mesh had its own skeleton.
The only available skeleton is the designated male_skeleton mesh.
Could the mesh please be applied to all the character and animal meshes? 

Alternatively, I would like to know if there is a way to apply the skeleton to the other models manually, as I have not managed to do it myself.

**Comment by Kindrad** [comment]
Closed for old.
