### ISSUE TITLE
Exports in the format .mesh.xml

### ISSUE THREAD

**Issue by Kirosawa** [Kindrad/Kenshi_IO_Continued#3]
Hi! In Blender versions 3.4 and 3.6, all exported models have xml format. The exported file looks like this xxxxxxxx.mesh.xml . If you rename and remove the xml at the end, and then throw it into the game, then the game breaks. I installed the plugin according to your instructions. Maybe I'm doing something wrong?
![2023-08-05 202547](https://github.com/Kindrad/Kenshi_IO_Continued/assets/38048978/e63d8ed6-97b4-44c6-a7cc-1dce3c401d55)

**Comment by Kindrad** [comment]
While 3.6 might have some issues I recall it working just fine through Blender 3.5. 3.5 was the last time I both used and updated the add-on and it was working fine for me then.

Does Blender show an error during export process? Any additional info such as the export parameters or anything you think might be relevant would be helpful.

**Comment by Kindrad** [comment]
More context.

The .mesh.xml is an intermediate format. The plugin first generates an xml and then the xml is converted to the Kenshi mesh format. The conversion is done by one of the .exe files bundled with the addon. It could be that Blender doesn't have enough permissions for the addon to function.

**Comment by Kirosawa** [comment]
Blender 3.5 has the same problem. Blender does not give any errors when exporting or importing.
![Снимок экрана 2023-08-06 094532](https://github.com/Kindrad/Kenshi_IO_Continued/assets/38048978/4dbbe878-45fc-450c-af62-a18e06c64fdb)
![Снимок экрана 2023-08-06 100349](https://github.com/Kindrad/Kenshi_IO_Continued/assets/38048978/214b28ba-190c-4aae-9e41-ead99fb4a67d)

**Comment by Kindrad** [comment]
Sorry for getting back late.

I can't seem to reproduce the problem on my end so I can't really debug for it. I'd suggest to try reinstalling the add-on or running Blender with admin privileges.

If neither of those work consider dropping by the [Kenshi Community Discord](https://discord.gg/5Z8qXPF) if you use Discord. There are quite a few people there who use IO_Continued and might have ran into and resolved the issue themselves.

**Comment by Kirosawa** [comment]
Anyway, thanks for the help! ;) 
My new laptop should arrive in a week, maybe the addon will work on it.

**Comment by Kirosawa** [comment]
Hello again! When trying to export a model to .mesh, this error appears. Does she mean anything to you?
![2023-08-29 132921](https://github.com/Kindrad/Kenshi_IO_Continued/assets/38048978/48ded5e9-7bf7-40be-93f9-99e561399ec9)

**Comment by Kindrad** [comment]
Hey sorry for late response. The divide by zero error for weights is now fixed (The one you posted). You can get the new updates to fix that bug. Going to close this issue, if you have any more feel free to open up a new one with new error.
