### ISSUE TITLE
"Index out of range"

### ISSUE THREAD

**Issue by GrizzlyOne95** [Kindrad/Kenshi_IO_Continued#5]
Hello,
I'm getting an error trying to export a mesh with this plugin, even with an import and then export with no changes. Is there a way to resolve this, or get more info on why its happening? 

Python: Traceback (most recent call last):
  File "C:\Users\iestu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_mesh_kenshi_continued\__init__.py", line 410, in execute
    result = OgreExport.save(self, context, **keywords)
  File "C:\Users\iestu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_mesh_kenshi_continued\OgreExport.py", line 1243, in save
    bCollectSkeletonData(blenderMeshData, selectedObjects)
  File "C:\Users\iestu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_mesh_kenshi_continued\OgreExport.py", line 1102, in bCollectSkeletonData
    skeleton = Skeleton(selectedObjects[0])
  File "C:\Users\iestu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_mesh_kenshi_continued\OgreExport.py", line 212, in __init__
    self.bones[self.ids[bone.name]] = bone
IndexError: list assignment index out of range

**Comment by GrizzlyOne95** [comment]
Blender 3.3 and 3.5 are same result

**Comment by Kindrad** [comment]
Based on the last error it appears that there is a mismatch between the bone names and vertex groups in the mesh being attached to the skeleton. For example there might be a "Bone 3" in the mesh but there is no "Bone 3" on the skeleton.

Make sure there aren't any extra bone weights assigned on the mesh that aren't in the skeleton. That _should_ fix this particular error.

When I have the time I'll have to update the addon to handle this error more gracefully.

If you haven't visited already, Kenshi Community Discord or Genesis Modding Guild (See Genesis mod page on Steam Workshop) are both good resources for help. Both for asking about/resolving errors and general modding advice.

**Comment by GrizzlyOne95** [comment]
Alright sounds good, thanks. I'm actually using this plugin for the game Battlezone 98 Redux which also uses Ogre engine and has ZERO tools of its own for getting models into the game. It works flawlessly for the most part, so thank you for your work on this. 

Edit: I was a bit confused because the plugin imported my mesh just fine but with 0 edits/changes it wouldn't export it as is.

**Comment by Kindrad** [comment]
Did altering the mesh vertex groups end up working for solving this issue?

**Comment by GrizzlyOne95** [comment]
Thanks for your fix on this! Very helpful! :D
