### ISSUE TITLE
There is no import Kenshi Collision (.xml) files functionality

### ISSUE THREAD

**Issue by VolodymyrTesliuk** [Kindrad/Kenshi_IO_Continued#6]
- Will it be posible to add that feature?
- OR is there any workarounds for that?

Thanks

**Comment by Kindrad** [comment]
Hi sorry for really late response to this. It's not impossible though not really something on my radar for immediate addition either. It's in the "nice to have" category of features if I find myself doing a rewrite or get more requests for such a feature. This is the first time someone has asked for this specifically.

The addon has limited xml export functionality (box and mesh colliders) and that seems to be enough for buildings and such.
