### ISSUE TITLE
Syntax error on install

### ISSUE THREAD

**Issue by ReiKGT** [Kindrad/Kenshi_IO_Continued#9]
![error](https://github.com/Kindrad/Kenshi_IO_Continued/assets/4693152/4e087e93-10aa-4cc5-87fe-3e5f96468781)
When attempting to toggle on use of the plugin I get this syntax error.

**Comment by Kindrad** [comment]
As of a recent update IO_Continued now only supports Blender 3.3 and higher. Sorry for the inconvenience.
